name: Feature request
description: Propose a new runtime, scheduler, or benchmark capability.
title: "[Feature] "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What user or developer problem are you trying to solve?
      placeholder: Describe the gap or pain point.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred solution.
      placeholder: API shape, behavior, and expected outcome.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered.

  - type: textarea
    id: impact
    attributes:
      label: Expected impact
      description: How should we evaluate success?
      placeholder: Quality, latency, cost, usability, etc.
